// push argument 1
@1
                                D=A
                                @ARG
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// pop pointer 1
@SP
                                 A=M-1
                                 D=M
                                 @13
                                 M=D
                                 @SP
                                 M=M-1
                                 @1
                                 D=A
                                 @3
                                 D=D+A
                                 @14
                                 M=D
                                 @13
                                 D=M
                                 @14
                                 A=M
                                 M=D
// push constant 0
@0
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// pop that 0
@SP
                                 A=M-1
                                 D=M
                                 @13
                                 M=D
                                 @SP
                                 M=M-1
                                 @0
                                 D=A
                                 @THAT
                                 D=D+M
                                 @14
                                 M=D
                                 @13
                                 D=M
                                 @14
                                 A=M
                                 M=D
// push constant 1
@1
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// pop that 1
@SP
                                 A=M-1
                                 D=M
                                 @13
                                 M=D
                                 @SP
                                 M=M-1
                                 @1
                                 D=A
                                 @THAT
                                 D=D+M
                                 @14
                                 M=D
                                 @13
                                 D=M
                                 @14
                                 A=M
                                 M=D
// push argument 0
@0
                                D=A
                                @ARG
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// push constant 2
@2
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// sub
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D-M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// pop argument 0
@SP
                                 A=M-1
                                 D=M
                                 @13
                                 M=D
                                 @SP
                                 M=M-1
                                 @0
                                 D=A
                                 @ARG
                                 D=D+M
                                 @14
                                 M=D
                                 @13
                                 D=M
                                 @14
                                 A=M
                                 M=D
// label MAIN_LOOP_START
(MAIN_LOOP_START)
// push argument 0
@0
                                D=A
                                @ARG
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// if-goto COMPUTE_ELEMENT
@SP
                     A=M-1
                     D=M
                     @SP
                     M=M-1
                     @COMPUTE_ELEMENT
                     D;JNE
// goto END_PROGRAM
@END_PROGRAM
                     D;JMP
// label COMPUTE_ELEMENT
(COMPUTE_ELEMENT)
// push that 0
@0
                                D=A
                                @THAT
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// push that 1
@1
                                D=A
                                @THAT
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// pop that 2
@SP
                                 A=M-1
                                 D=M
                                 @13
                                 M=D
                                 @SP
                                 M=M-1
                                 @2
                                 D=A
                                 @THAT
                                 D=D+M
                                 @14
                                 M=D
                                 @13
                                 D=M
                                 @14
                                 A=M
                                 M=D
// push pointer 1
@1
                                D=A
                                @3
                                A=D+A
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// push constant 1
@1
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// pop pointer 1
@SP
                                 A=M-1
                                 D=M
                                 @13
                                 M=D
                                 @SP
                                 M=M-1
                                 @1
                                 D=A
                                 @3
                                 D=D+A
                                 @14
                                 M=D
                                 @13
                                 D=M
                                 @14
                                 A=M
                                 M=D
// push argument 0
@0
                                D=A
                                @ARG
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// push constant 1
@1
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// sub
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D-M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// pop argument 0
@SP
                                 A=M-1
                                 D=M
                                 @13
                                 M=D
                                 @SP
                                 M=M-1
                                 @0
                                 D=A
                                 @ARG
                                 D=D+M
                                 @14
                                 M=D
                                 @13
                                 D=M
                                 @14
                                 A=M
                                 M=D
// goto MAIN_LOOP_START
@MAIN_LOOP_START
                     D;JMP
// label END_PROGRAM
(END_PROGRAM)
(END1)
                                @END1
                                0;JMP
