// function SimpleFunction.test 2
(SimpleFunction.test)
                     @2
                     D=A
                     @13
                     M=D
                     @i
                     M=0
                     (SimpleFunction.test$LOOP)
                     @13
                     D=M-1
                     M=M-1
                     @SimpleFunction.test$END
                     D;JLT
                     @i
                     D=M
                     @LCL
                     A=M+D
                     M=0
                     @i
                     M=M+1
                     @SP
                     M=M+1
                     @SimpleFunction.test$LOOP
                     1;JMP
                     (SimpleFunction.test$END)
// push local 0
@0
                                D=A
                                @LCL
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// push local 1
@1
                                D=A
                                @LCL
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// not
@SP
                            A=M-1
                            M=!M
// push argument 0
@0
                                D=A
                                @ARG
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// push argument 1
@1
                                D=A
                                @ARG
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// sub
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D-M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// return
@LCL
                     D=M
                     @13
                     M=D
                     @5
                     D=D-A
                     A=D
                     D=M
                     @14
                     M=D
                     @SP
                     A=M-1
                     D=M
                     @ARG
                     A=M
                     M=D
                     @ARG
                     D=M+1
                     @SP
                     M=D
                     @1
                     D=A
                     @13
                     A=M-D
                     D=M
                     @THAT
                     M=D
                     @2
                     D=A
                     @13
                     A=M-D
                     D=M
                     @THIS
                     M=D
                     @3
                     D=A
                     @13
                     A=M-D
                     D=M
                     @ARG
                     M=D
                     @4
                     D=A
                     @13
                     A=M-D
                     D=M
                     @LCL
                     M=D
                     @14
                     A=M
                     D;JMP
(END1)
                                @END1
                                1;JMP
