@256
                                                D=A
                                                @SP
                                                M=D
// call Sys.init
@return-address-Sys.init1
                     D=A
                     @SP
                     A=M
                     M=D
                     @SP
                     M=M+1
                     @LCL
                     D=M
                     @SP
                     A=M
                     M=D
                     @SP
                     M=M+1
                     @ARG
                     D=M
                     @SP
                     A=M
                     M=D
                     @SP
                     M=M+1
                     @THIS
                     D=M
                     @SP
                     A=M
                     M=D
                     @SP
                     M=M+1
                     @THAT
                     D=M
                     @SP
                     A=M
                     M=D
                     @SP
                     M=M+1
                     @0
                     D=A
                     @13
                     M=D
                     @5
                     D=A
                     @13
                     M=D+M
                     @SP
                     D=M
                     @ARG
                     M=D
                     @13
                     D=M
                     @ARG
                     M=M-D
                     @SP
                     D=M
                     @LCL
                     M=D
                     @Sys.init
                     D;JMP
                     (return-address-Sys.init1)
// function Sys.init 0
(Sys.init)
                     @0
                     D=A
                     @13
                     M=D
                     @i
                     M=0
                     (Sys.init$LOOP)
                     @13
                     D=M-1
                     M=M-1
                     @Sys.init$END
                     D;JLT
                     @i
                     D=M
                     @LCL
                     A=M+D
                     M=0
                     @i
                     M=M+1
                     @SP
                     M=M+1
                     @Sys.init$LOOP
                     1;JMP
                     (Sys.init$END)
// push constant 4000
@4000
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// pop pointer 0
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @0
                                     D=A
                                     @3
                                     D=D+A
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                     M=D
// push constant 5000
@5000
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// pop pointer 1
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @1
                                     D=A
                                     @3
                                     D=D+A
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                     M=D
// call Sys.main 0
@return-address-Sys.main2
                     D=A
                     @SP
                     A=M
                     M=D
                     @SP
                     M=M+1
                     @LCL
                     D=M
                     @SP
                     A=M
                     M=D
                     @SP
                     M=M+1
                     @ARG
                     D=M
                     @SP
                     A=M
                     M=D
                     @SP
                     M=M+1
                     @THIS
                     D=M
                     @SP
                     A=M
                     M=D
                     @SP
                     M=M+1
                     @THAT
                     D=M
                     @SP
                     A=M
                     M=D
                     @SP
                     M=M+1
                     @0
                     D=A
                     @13
                     M=D
                     @5
                     D=A
                     @13
                     M=D+M
                     @SP
                     D=M
                     @ARG
                     M=D
                     @13
                     D=M
                     @ARG
                     M=M-D
                     @SP
                     D=M
                     @LCL
                     M=D
                     @Sys.main
                     D;JMP
                     (return-address-Sys.main2)
// pop temp 1
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @1
                                     D=A
                                     @5
                                     D=D+A
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                    M=D
// label LOOP
(LOOP)
// goto LOOP
@LOOP
                     D;JMP
// function Sys.main 5
(Sys.main)
                     @5
                     D=A
                     @13
                     M=D
                     @i
                     M=0
                     (Sys.main$LOOP)
                     @13
                     D=M-1
                     M=M-1
                     @Sys.main$END
                     D;JLT
                     @i
                     D=M
                     @LCL
                     A=M+D
                     M=0
                     @i
                     M=M+1
                     @SP
                     M=M+1
                     @Sys.main$LOOP
                     1;JMP
                     (Sys.main$END)
// push constant 4001
@4001
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// pop pointer 0
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @0
                                     D=A
                                     @3
                                     D=D+A
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                     M=D
// push constant 5001
@5001
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// pop pointer 1
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @1
                                     D=A
                                     @3
                                     D=D+A
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                     M=D
// push constant 200
@200
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// pop local 1
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @1
                                     D=A
                                     @LCL
                                     D=D+M
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                     M=D
// push constant 40
@40
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// pop local 2
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @2
                                     D=A
                                     @LCL
                                     D=D+M
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                     M=D
// push constant 6
@6
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// pop local 3
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @3
                                     D=A
                                     @LCL
                                     D=D+M
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                     M=D
// push constant 123
@123
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// pop temp 0
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @0
                                     D=A
                                     @5
                                     D=D+A
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                    M=D
// push local 0
@0
                                    D=A
                                    @LCL
                                    A=D+M
                                    D=M
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// push local 1
@1
                                    D=A
                                    @LCL
                                    A=D+M
                                    D=M
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// push local 2
@2
                                    D=A
                                    @LCL
                                    A=D+M
                                    D=M
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// push local 3
@3
                                    D=A
                                    @LCL
                                    A=D+M
                                    D=M
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// push local 4
@4
                                    D=A
                                    @LCL
                                    A=D+M
                                    D=M
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// return
@LCL
                     D=M
                     @13
                     M=D
                     @5
                     D=D-A
                     A=D
                     D=M
                     @14
                     M=D
                     @SP
                     A=M-1
                     D=M
                     @ARG
                     A=M
                     M=D
                     @ARG
                     D=M+1
                     @SP
                     M=D
                     @1
                     D=A
                     @13
                     A=M-D
                     D=M
                     @THAT
                     M=D
                     @2
                     D=A
                     @13
                     A=M-D
                     D=M
                     @THIS
                     M=D
                     @3
                     D=A
                     @13
                     A=M-D
                     D=M
                     @ARG
                     M=D
                     @4
                     D=A
                     @13
                     A=M-D
                     D=M
                     @LCL
                     M=D
                     @14
                     A=M
                     D;JMP
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// push constant 4002
@4002
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// pop pointer 0
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @0
                                     D=A
                                     @3
                                     D=D+A
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                     M=D
// push constant 5002
@5002
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// pop pointer 1
@SP
                                     A=M-1
                                     D=M
                                     @13
                                     M=D
                                     @SP
                                     M=M-1
                                     @1
                                     D=A
                                     @3
                                     D=D+A
                                     @14
                                     M=D
                                     @13
                                     D=M
                                     @14
                                     A=M
                                     M=D
// push argument 0
@0
                                    D=A
                                    @ARG
                                    A=D+M
                                    D=M
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// push constant 12
@12
                                    D=A
                                    @SP
                                    A=M
                                    M=D
                                    @SP
                                    M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// return
@LCL
                     D=M
                     @13
                     M=D
                     @5
                     D=D-A
                     A=D
                     D=M
                     @14
                     M=D
                     @SP
                     A=M-1
                     D=M
                     @ARG
                     A=M
                     M=D
                     @ARG
                     D=M+1
                     @SP
                     M=D
                     @1
                     D=A
                     @13
                     A=M-D
                     D=M
                     @THAT
                     M=D
                     @2
                     D=A
                     @13
                     A=M-D
                     D=M
                     @THIS
                     M=D
                     @3
                     D=A
                     @13
                     A=M-D
                     D=M
                     @ARG
                     M=D
                     @4
                     D=A
                     @13
                     A=M-D
                     D=M
                     @LCL
                     M=D
                     @14
                     A=M
                     D;JMP
(END3)
                                @END3
                                1;JMP
