// push constant 3030
@3030
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// pop pointer 0
@SP
                             A=M-1
                             D=M
                             @13
                             M=D
                             @SP
                             M=M-1
                             @0
                             D=A
                             @3
                             D=D+A
                             @14
                             M=D
                             @13
                             D=M
                             @14
                             A=M
                             M=D
// push constant 3040
@3040
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// pop pointer 1
@SP
                             A=M-1
                             D=M
                             @13
                             M=D
                             @SP
                             M=M-1
                             @1
                             D=A
                             @3
                             D=D+A
                             @14
                             M=D
                             @13
                             D=M
                             @14
                             A=M
                             M=D
// push constant 32
@32
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// pop this 2
@SP
                             A=M-1
                             D=M
                             @13
                             M=D
                             @SP
                             M=M-1
                             @2
                             D=A
                             @THIS
                             D=D+M
                             @14
                             M=D
                             @13
                             D=M
                             @14
                             A=M
                             M=D
// push constant 46
@46
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// pop that 6
@SP
                             A=M-1
                             D=M
                             @13
                             M=D
                             @SP
                             M=M-1
                             @6
                             D=A
                             @THAT
                             D=D+M
                             @14
                             M=D
                             @13
                             D=M
                             @14
                             A=M
                             M=D
// push pointer 0
@0
                                D=A
                                @3
                                A=D+A
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// push pointer 1
@1
                                D=A
                                @3
                                A=D+A
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// push this 2
@2
                                D=A
                                @THIS
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// sub
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D-M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// push that 6
@6
                                D=A
                                @THAT
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
(END1)
                                @END1
                                0;JMP
