// push constant 0
@0
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// pop local 0
@SP
                                 A=M-1
                                 D=M
                                 @13
                                 M=D
                                 @SP
                                 M=M-1
                                 @0
                                 D=A
                                 @LCL
                                 D=D+M
                                 @14
                                 M=D
                                 @13
                                 D=M
                                 @14
                                 A=M
                                 M=D
// label LOOP_START
(LOOP_START)
// push argument 0
@0
                                D=A
                                @ARG
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// push local 0
@0
                                D=A
                                @LCL
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// add
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D+M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// pop local 0
@SP
                                 A=M-1
                                 D=M
                                 @13
                                 M=D
                                 @SP
                                 M=M-1
                                 @0
                                 D=A
                                 @LCL
                                 D=D+M
                                 @14
                                 M=D
                                 @13
                                 D=M
                                 @14
                                 A=M
                                 M=D
// push argument 0
@0
                                D=A
                                @ARG
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// push constant 1
@1
                                D=A
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// sub
@SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            M=D
                            @SP
                            A=M-1
                            D=M
                            @SP
                            M=M-1
                            @13
                            D=D-M
                            @SP
                            A=M
                            M=D
                            @SP
                            M=M+1
// pop argument 0
@SP
                                 A=M-1
                                 D=M
                                 @13
                                 M=D
                                 @SP
                                 M=M-1
                                 @0
                                 D=A
                                 @ARG
                                 D=D+M
                                 @14
                                 M=D
                                 @13
                                 D=M
                                 @14
                                 A=M
                                 M=D
// push argument 0
@0
                                D=A
                                @ARG
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
// if-goto LOOP_START
@SP
                     A=M-1
                     D=M
                     @SP
                     M=M-1
                     @LOOP_START
                     D;JNE
// push local 0
@0
                                D=A
                                @LCL
                                A=D+M
                                D=M
                                @SP
                                A=M
                                M=D
                                @SP
                                M=M+1
(END1)
                                @END1
                                0;JMP
